---
# - name: Creates 'code' folder
#   file: path="{{ code_folder }}" state=directory owner="{{ mac_username }}" group=staff

# - name: Creates '.ssh' folder
#   file: path="{{ ssh_folder }}" state=directory owner="{{ mac_username }}" group=staff

- include: textmate2.yml 
  vars:
    home_folder: "{{ home_folder }}"

- include: zsh.yml
  vars:
    home_folder: "{{ home_folder }}"
    github_home: "{{ github_home }}"
