---
# - name: Creates 'code' folder
#   file: path="{{ code_folder }}" state=directory owner="{{ mac_username }}" group=staff

# - name: Creates '.ssh' folder
#   file: path="{{ ssh_folder }}" state=directory owner="{{ mac_username }}" group=staff

# textmate 2 settings
- copy: src=".tm_properties" dest="{{ home_folder }}/.tm_properties" force=yes

# ZSH related items
- name: Determine if zsh is the current shell
  shell: 'echo $SHELL'
  register: default_shell
  sudo: no

- name: make zsh default if not already
  shell:  chsh -s /bin/zsh 
  when: default_shell.stdout.find('/bin/zsh') == -1

- git: repo=https://github.com/wchrisjohnson/prezto.git 
       dest="{{ home_folder }}/.zprezto"
       recursive=yes
       update=yes

- file: src="{{ home_folder }}/.zprezto//runcoms/{{ item }}"
        dest="{{ home_folder }}/.{{ item }}"
        state=link
  with_items:
    - 'zlogin'
    - 'zlogout'
    - 'zpreztorc'
    - 'zprofile'
    - 'zshenv'
    - 'zshrc'
